### ISSUE TITLE
Tracking file and directory changes with a leading ~

### ISSUE THREAD

**Issue by alloro** [fishgretel/fasd#10]
When jumping to directories or editing files with a leading `~` the plugin won't recognize it and furthermore won't add it to the `~/.fasd` file.

Example:
`cd /home/<user>/Documents` results in a line in the `.fasd`
`cd ~/Documents` won't result in a line

> same for file manipulation

`nano /home/<user>/.Xresources` will result in a line
`nano ~/.Xresources` won't 

> This behaviour isn't happening in bash or zsh (both tested :white_check_mark: ). Perhaps due to the fact of putting 'eval "$(fasd --init auto)' in their rc files.

**Comment by adityavm** [comment]
@alloro @gretel i've submitted a PR #12 fixing both #8 and this
