### ISSUE TITLE
unable to properly pipe commands with conf.d/__fasd_run.fish

### ISSUE THREAD

**Issue by pekcheey** [fishgretel/fasd#18]
when __fasd_run.fish is in effect, piping from aws resulted in the command being piped not the content

```
debian@debian10 ~/.c/f/conf.d> aws --version > /t/c
debian@debian10 ~/.c/f/conf.d> cat /t/c
aws --version
debian@debian10 ~/.c/f/conf.d> file (which aws)
/home/debian/.local/bin/aws: Python script, ASCII text executable
```

it works fine after I remove the file.

```
debian@debian10 ~/.c/fish> rm conf.d/__fasd_run.fish
debian@debian10 ~/.c/fish> fish
Welcome to fish, the friendly interactive shell
debian@debian10 ~/.c/fish> aws --version > /t/c
debian@debian10 ~/.c/fish> cat /t/c
aws-cli/1.18.211 Python/3.7.3 Linux/4.19.0-13-amd64 botocore/1.19.51
debian@debian10 ~/.c/fish>
```
I'm not sure if this is a problem with my configuration or something. 
I've a hunch that it might be related to the fact that ```aws``` is a python script.
Anyway, I'm running in tmux under byobu in debian10 in a virtual machine with vmplayer. 
it's a relatively new machine.

```
debian@debian10 ~/.c/fish> fish --version
fish, version 3.0.2

```

**Comment by ridiculousfish** [comment]
I took a look but I am not sure how to reproduce this - I am not sure what`__fasd_run.fish` is, and my aws is not a Python script. Can you please provide steps to reproduce, or narrow it down on your end?

**Comment by ridiculousfish** [comment]
I am not sure how to reproduce this. Does `type python` or `type aws` change when `__fasd_run.fish` is active?

**Comment by pekcheey** [comment]
nope. they do not change.

```
# when __fasd_run.fish is not active
debian@debian10 ~> type aws
aws is /home/debian/.local/bin/aws
debian@debian10 ~> type python
python is /usr/bin/python
debian@debian10 ~> aws --version > /t/c
debian@debian10 ~> cat /t/c
aws-cli/1.18.211 Python/3.7.3 Linux/4.19.0-13-amd64 botocore/1.19.51

# when __fasd_run.fish is active
debian@debian10 ~> type aws
aws is /home/debian/.local/bin/aws
debian@debian10 ~> type python
python is /usr/bin/python
debian@debian10 ~> aws --version > /t/c
debian@debian10 ~> cat /t/c
aws --version
debian@debian10 ~> 
```

I realise that it's nothing to do with aws or python apparently; pwd have the same behaviour.
for this test I'm not using tmux.  

```
# when __fasd_run.fish is active
debian@debian10 ~> pwd > /t/c
debian@debian10 ~> cat /t/c
pwd
debian@debian10 ~> pwd
/home/debian
debian@debian10 ~> exit
debian@debian10:~$ rm .config/fish/conf.d/__fasd_run.fish 
debian@debian10:~$ fish
Welcome to fish, the friendly interactive shell
debian@debian10 ~> pwd > /t/c
debian@debian10 ~> cat /t/c
/home/debian
debian@debian10 ~> 
```

are you not able to replicate this? if so the problem might be something peculiar to my particular setup. 
We could simply close this if that's the case. 
since I would imagine a lot of complaints if this is a generic problem. : D

```
#my fisher plugin if you would like to try to replicate this
debian@debian10 ~/.c/fish> fisher list
jorgebucaran/fisher
jethrokuan/fzf
fishgretel/fasd
```

**Comment by pekcheey** [comment]
hey, it look like this issue is the same / related to #17

**Comment by gretel** [comment]
> since I would imagine a lot of complaints if this is a generic problem. :

you are welcome to provide a PR.

**Comment by pekcheey** [comment]
I've tested  #20 and it does resolve the issue I had. 
Thanks!

**Comment by gretel** [comment]
@pekcheey thank you, did merge.
