### ISSUE TITLE
Tab completion?

### ISSUE THREAD

**Issue by nyarly** [fishgretel/fasd#3]
It'd be great to be able to do (from the `fasd` man page) `vim d,ngin,conf<Tab>` or at least `vim nginx,conf<Alt-Z>` How possible would that be?

**Comment by tejasvi** [comment]
Since this issue is closed, I am wondering if there is a way since I can't get tab completion to work as well. My current workaround is `vi (f nginx<Tab>`

**Comment by gretel** [comment]
i'm open to accept PR but can't work on this myself right now.
