### ISSUE TITLE
record files

### ISSUE THREAD

**Issue by nhooyr** [fishgretel/fasd#7]
fasd on zsh/bash also takes care of figuring out files used in the arguments to commands.

**Comment by nhooyr** [comment]
This is solved by https://github.com/oh-my-fish/plugin-fasd

See https://github.com/oh-my-fish/plugin-fasd/pull/10 for how.

**Comment by paradox460** [comment]
Opened a PR for fixing this in #8

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
